local repo = 'https://raw.githubusercontent.com/mstudio45/LinoriaLib/main/'
local Library = loadstring(game:HttpGet(repo .. 'Library.lua'))()
local ThemeManager = loadstring(game:HttpGet(repo .. 'addons/ThemeManager.lua'))()
local SaveManager = loadstring(game:HttpGet(repo .. 'addons/SaveManager.lua'))()
Library:Notify("[Notifier From Discord] : Join https://discord.gg/mshub to get script MSHUB.")
wait(5)
Library:Notify("You will kick in")
wait(2)
Library:Notify("3")
wait(2)
Library:Notify("2")
wait(2)
Library:Notify("1")
wait(2)
game.Players.LocalPlayer:Kick("You Not Time")
